import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <head>
                <meta
                    property="og:title"
                    content="Invitación de XV Años - Tatiana Palacios"
                />
                <meta
                    property="og:description"
                    content="¡Celebra los XV años de Tatiana con nosotros! Fecha: 1 de Marzo de 2025. Lugar: Casa de la familia"
                />
                <meta property="og:image" content="/page.png" />
                <meta property="og:url" content="https://tudominio.com" />
                <meta property="og:type" content="website" />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
            >
                
                {children}
            </body>
        </html>
    );
}
